### ISSUE TITLE
change title link from $osutop

### ISSUE THREAD

**Issue by Ludeo** [stageosu/Kaguya#10]
When you click on the userprofile link from the osutop command, you get to the site 

`https://osu.ppy.sh/u/{username}/`

With that link people which are using the old design can't access the profile. So the link should be changed to the following, so you can access the profile with both designs:

`https://osu.ppy.sh/u/{username}`

**Comment by hburn7** [comment]
I fixed another issue related to the link, that's why I closed it. Will fix the slash in the next update
