### ISSUE TITLE
"Kaguya is typing..." indefinitely with $profile

### ISSUE THREAD

**Issue by Panda28007** [stageosu/Kaguya#135]
**Describe the bug** - *What command does this bug belong to (if applicable)? Is there a service that should be triggering but isn't? Delete this text and write a clear and concise description of the bug in a few sentences.*
Wen you use $profile the bot starts typing endlessly.
**To Reproduce** - *Please write a few steps that need to be taken for this bug to be produced:*

1.use the cmd $profile
2.after wait and you will see the bug
3.
4.
5.

**Expected behavior** - *A clear and concise description of what you expected to happen.*

**Screenshots** - *If applicable, add links to any screenshots that help explain the problem.*

**Version** - *The version of Kaguya that caused this bug.*
- For v2.0 open beta, this may look like `v2.0.A2020.x.y`.
- For live, this may look like `v2.x`

**Additional context** - *Is there anything else that should be noted about the bug?*

**Comment by hburn7** [comment]
Hey, thank you for reporting this bug. It looks like the "Kaguya is typing..." goes away after the profile image is sent, but then comes back a few seconds later and stays indefinitely.

I can see how this is inconvenient. I'll have this fixed in the next patch.

**Comment by Panda28007** [comment]
Thx for fix this bug

**Comment by hburn7** [comment]
Fixed in 668741ec610eb3c24b2f79ced5cb175afc3e27c9
