### ISSUE TITLE
problem with $massblacklist and $unblacklist

### ISSUE THREAD

**Issue by Ludeo** [stageosu/Kaguya#17]
When I typed in `$massblacklist <user>` it banned the user and blacklisted him. Then I looked in the accounts.json and it only says `Blacklisted: 1` for the person I blacklisted. Thats alright like that but the username is `null`. I tried to unblacklist the user so I typed in `$unblacklist <ID>`. The output in the console is:
`User not found.`

**Comment by hburn7** [comment]
I will work on making the "name" portion of each user account update faster. It takes someone typing in chat at least once (or even using a command) to have their name set in the file. I will look into scraping the server for everyone and creating a profile for everyone automatically.

**Comment by hburn7** [comment]
Lol I didn't mean to close it, but I will also look into the ID thing you mentioned.
