### ISSUE TITLE
Old Commands Reborn

### ISSUE THREAD

**Issue by MrGforces** [stageosu/Kaguya#172]
I really miss all Kaguya Bot's Ancient Ancestor's commands, and i need them. Can you add some of them again? Such as :
• $avatar (The one that send images for your avatar)
• $wallpaper (The one that send images for your wallpaper)
• Etc.

**Comment by hburn7** [comment]
Hey,

I don't remember any commands from before [Version 2](https://github.com/kaguyabot/Kaguya/tree/master/KaguyaProjectV2/KaguyaBot/Core/Commands). If you have any more requests feel free to reply to this and let me know what they are and a detailed description of what the command does, and I will do my best to include it in v4.

**Comment by MrGforces** [comment]
More Old Commands that i've found :
$nekoavatar (Of course, send an Neko Avatar images)
$waifu (Yup, send Waifus images)

**Comment by hburn7** [comment]
Implemented

**Comment by hburn7** [comment]
$wallpaper still needs to be implemented

**Comment by hburn7** [comment]
Implemented in #179
