### ISSUE TITLE
Poll Command

### ISSUE THREAD

**Issue by MrGforces** [stageosu/Kaguya#175]
Add Poll Commands. So we can start polls if we need to decide something, but we confused.

The command should looks like :

`$poll create -c [Channel] -t [Time] -s1 (First Selection -s2 [Second Selection]...(Up to ?) -d <Description>`

Example : In the picture (You can change some words on "what the bot will send" to make it looks better, but that how it should looks like)

![Screenshot_2020-12-29-23-05-47-83](https://user-images.githubusercontent.com/73664628/103298023-19650780-4a2c-11eb-9461-def4008f3079.png)

**Comment by hburn7** [comment]
Thanks for the well-written example. This gives me a better idea at how something like this would be implemented.
