### ISSUE TITLE
$timely isn't working

### ISSUE THREAD

**Issue by Ludeo** [stageosu/Kaguya#19]
When I type in `$timely` the bots responds is 
![cOoBOJq](https://user-images.githubusercontent.com/36997936/54860380-6bd2a980-4d19-11e9-97ab-6e73a0017c04.png)
I guess it's a problem with `timeout = timelyConfig.timelyHours;` because when I let it output it with `Console.WriteLine(timelyConfig.timelyHours);` I get the output 0

**Comment by hburn7** [comment]
Closed in 1.4.2
