### ISSUE TITLE
Feature Request: reports, command toggles, specific roles to execute commands.

### ISSUE THREAD

**Issue by MrGforces** [stageosu/Kaguya#200]
**Report Feature**
If server's members saw something that are against the rules, they can report it using this command. After someone sent a report, it will show up in specific channel (We can set it).
`$report -n [Mention/ID of Rules Breaker] -d [Description of your report]`
Example : `$report -n Example#6969 -d Racism`

**Toggle Enable/Disable Features/Commands**
We can enable and/or disable some features.
`$togglefeature -f [Feature] -t [Toggle Enable/Disable]
Example : `$togglefeature -f nsfw -t disable`

**Specific Permissions/Roles to Use Commands**
Only the members that own the permissions/roles that be ablw to use the commands.

**Comment by hburn7** [comment]
I think the `$report` and `$togglefeature` suggestions are great. I think limiting commands to a certain role is a bit complicated. Instead, there is (or will be) a channel blacklist command where server admins can control which text channels Kaguya will respond in. What you could do is blacklist all channels except ones that are only usable by members with a certain role.
