### ISSUE TITLE
`$user` Command

### ISSUE THREAD

**Issue by MrGforces** [stageosu/Kaguya#254]
Put commands that related to one or more users in one command, called `$user`. It's included the commands like `$ban`, `$kick`, etc. on it.

Command :
`$user -u/user <@/ID(use *,* between 2 *users* to add more  users)> -a/action <action(use *,* between 2 *action* to add more action)>`
Example :
`$user -u @FS MrGforces#3503, -a tempmute 6h9m noob`

**Comment by hburn7** [comment]
Hmm. I feel like this is a bit too complicated both codewise and user wise. I could see something like `$user -masskick <users>` or `$user -unban <user>` potentially being more simplistic, however.

**Comment by MrGforces** [comment]
Well, that more simple than what I showed. But I think the one that I showed (Maybe) can be swaped. I mean, you can swap the `-u baaa -a buu` to `-a buu -u baa`. Actually it was an idea from a game bot that i played, and it work really well.

**Comment by hburn7** [comment]
I won't be implementing this for right now as this would change too much existing functionality with the bot. Currently, there are several distinct modules that affect users. Throwing all of these into one "umbrella" module would be too confusing to new users and sort of goes against the command design we have at the moment. From a development standpoint, it would take too long to implement and correctly parse all possible arguments, it's just more efficient to add a new module for any user actions.
