### ISSUE TITLE
`$lockdown` Command

### ISSUE THREAD

**Issue by MrGforces** [stageosu/Kaguya#281]
Command for Admins to lockdown (Mute channels for all members/Hide channels for all members) some channels or the whole server, and simultaneously create a channel about the lockdown status.

Command :
`$lockdown -<#channel>  <#channel> <...> -[time]`
and
`$lockdown -server -[time]`
(If time not included, Admins will need to remove the lockdown with another command)
Example :
`$lockdown -#firstchannel #secondchannel -t 1d3h14m`
and
`$lockdown -server -1d3h14m`

**Comment by hburn7** [comment]
Very cool idea!
