### ISSUE TITLE
osuapikey not working

### ISSUE THREAD

**Issue by Ludeo** [stageosu/Kaguya#4]
I put my apikey in the config.json (Picture 1) and after restarting the bot I tried out osutop and it put out the following text in the console: "The Remoteserver has returned a error: (401) not authorized" (Picture 2)

Picture 1:
![issue](https://user-images.githubusercontent.com/36997936/54551684-d5b42180-49ae-11e9-970b-5001764e3be1.png)

Picture 2:
![unknown](https://user-images.githubusercontent.com/36997936/54551797-0d22ce00-49af-11e9-88ef-4ee1af8bfe1f.png)

**Comment by hburn7** [comment]
Are you using your bot's token and a proper command prefix symbol ($, #, etc) when the bot was running in picture 2?

**Comment by Ludeo** [comment]
Yes, but it wasn't safed in the config-file, just tipped them into the command prompt when I started the bot the first time. Now I put in the same bot-token and the same prefix into the config-file but its still giving me the same error.

**Comment by hburn7** [comment]
Ok so I've confirmed it is the API key that is throwing the error, I changed a number in my API key and it gave me the same 401 Error shown here. Try generating a new API key and ensuring it's pasted in exactly correctly. If that doesn't work I'll look deeper into this.

**Comment by Ludeo** [comment]
I genereated a new API key again and I did paste it correctly. It's still giving me the same error.

**Comment by hburn7** [comment]
This error only happens when the API key is in the wrong file...will look to delete the additional config files outside of the resources folder.
