### ISSUE TITLE
Fun part of help command is broken.

### ISSUE THREAD

**Issue by mmattbtw** [stageosu/Kaguya#89]
**Describe the bug** - When you go to to the fun part of help, it just says CSS.

**To Reproduce** - *Please write a few steps that need to be taken for this bug to be produced:*

1. @Kaguya 2.0 Help
2. Go To fun
3. just says CSS

**Expected behavior** - Shows what the fun commands do

**Screenshots** - [http://i.mmatt.pw/8HTFJnh4](http://i.mmatt.pw/8HTFJnh4)

**Version** - *The version of Kaguya that caused this bug.*
- For v2.0 open beta, this may look like `v2.0.A2020.x.y`.
- For live, this may look like `v2.x`

**Additional context** - *Is there anything else that should be noted about the bug?*

**Comment by hburn7** [comment]
Currently any command groups that just show `css` are there because there aren't any developed commands for those categories yet, thank you for submitting the report though.
